version: "3.9"

services:
  api:
    container_name: enrollments-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - enrollments-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - enrollments-network

volumes:
  rabbitmq_data:

networks:
    enrollments-network:
      external: true
